sudo: false
language: java
jdk:
- oraclejdk8
script:
- mvn -U -B clean compile findbugs:check package
addons:
  apt:
    packages:
    - libc6:i386
deploy:
  - provider: releases
    prerelease: true
    file:
      - target/fdsm.jar
      - target/fdsm.exe
    api-key:
      secure: "d0qmEDf0nGeEVUbbbevr/MOR8oaUnHt067G/F7je9mxmci6DNZp6hri4gcsIDRqG+tDVC3uWnc/raIoNUXDHv8Zbkk6PpMpmKM8w8nFfaut6QW6AiybeUGA9etfYk7sgLRCSdJ+6j1BoFnQnegsKXitlq65ZEXimxUgBZpHpw8c5rG0C8kMqr83s2Ddxd/UOpQ1zNGyydf3DWwmtAJNHU2HyB5LXh2itMEbMpCKe6wMuAAtO4Bpw0D2EP4yGC7bfUc72Djx40+Ltr5EKE8rvZTFI5/DJEO5IjtXNpasRbxCDjPcnB8T33/wFqYZirw2znPeGwhrrHgdeFvdgdCVtoyMmJ/OUWYVE6hCfEJcs09Ewe0JGX7SeP/sd/qEEPxIVx+pnV+mAG3rDu7pXEHPgSzOh3DhvN9VwYILN+p31CKfpWRhpgT9ptWkzQUep/a87LONk/6qLWFhVCWoXGViTIORGaqS69L2ySbMBHEHxod+z8c/GMsvlcZFKFO5iLFmxLIg7tvOZQoRziGo149hFE6N6vaZxuxbXQ+14AgsFZGdb8xAEXwWlYzW7IC/bD+4pIKQjxFllfnABhQ6IOJXvKCwT06W3Tkqp93eyW3K3LjPT5qrvPSNesFfJJdTOePy+z2q9IybHHoViJswsaO1uuYL6eNDvc/qDDYhRgId3gvs="
    skip_cleanup: true
    on:
      tags: true
      repo: fidesmo/fdsm
cache:
  directories:
  - $HOME/.m2
